name = "mom-masale-website"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mom-masale-db"
database_id = "cb5dcc52-dc4c-4439-8107-d38078479a00"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "mom-masale-images"
